# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72e84429a3bf22def8b39f1b3c8a6c830ab1a830d76b8de5ca515aa3fc3d9ab4c541f64fef0bf7f5846d3cadb8264934803ba9a365df2afe7e0c5ceb2eb0752f

test:
  secret_key_base: e7691129623df6bb782ee25d628111d97014d5caaa9b6c599b8b4f7719829e19aa979908bce8c2b1cc943985daec22971de5ff1b82c1084511f98e699e5d1458

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
